# Generated by Django 5.0 on 2024-04-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vencimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_para_vencimento_proximo', models.PositiveIntegerField(default=30, help_text='Número de dias para considerar um lote próximo do vencimento.')),
            ],
            options={
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
