# Generated by Django 5.0 on 2024-04-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vencimento', '0002_configuracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='notificacao_enviada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lote',
            name='responsavel_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Responsável'),
        ),
    ]
