# Generated by Django 5.0 on 2024-04-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vencimento', '0003_lote_notificacao_enviada_lote_responsavel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notificacoes', models.EmailField(max_length=254, verbose_name='E-mail para Notificações')),
            ],
        ),
    ]
