# Generated by Django 5.0 on 2024-04-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vencimento', '0004_configuracaoglobal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuracao',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='responsavel_email',
        ),
        migrations.AddField(
            model_name='configuracaoglobal',
            name='dias_para_vencimento_proximo',
            field=models.PositiveIntegerField(default=30, help_text='Número de dias para considerar um lote próximo do vencimento.'),
        ),
    ]
