# Generated by Django 5.0 on 2024-05-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vencimento', '0005_delete_configuracao_remove_lote_responsavel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque'),
        ),
    ]
