# Generated by Django 5.0 on 2024-05-15 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vencimento', '0008_casa_lote_casa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='casa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='vencimento.casa'),
        ),
    ]
