# Generated by Django 5.0 on 2024-05-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vencimento', '0009_alter_lote_casa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casa',
            options={'permissions': [('can_transfer', 'Can perform lot transfers')]},
        ),
        migrations.AddField(
            model_name='lote',
            name='transferido',
            field=models.BooleanField(default=False),
        ),
    ]
