# Generated by Django 5.0 on 2024-05-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vencimento', '0010_alter_casa_options_lote_transferido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='quantidade_atual',
        ),
        migrations.RemoveField(
            model_name='lote',
            name='transferido',
        ),
    ]
