# Generated by Django 5.0 on 2024-05-23 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vencimento', '0011_remove_lote_quantidade_atual_remove_lote_transferido'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='casa_destinada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes_destined', to='vencimento.casa', verbose_name='Casa Destinada'),
        ),
    ]
