# Generated by Django 5.0 on 2024-06-01 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vencimento', '0012_lote_casa_destinada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('AD', 'Adicionar'), ('TR', 'Transferir'), ('DE', 'Deletar'), ('RS', 'Registrar Saída')], max_length=2)),
                ('descricao', models.TextField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vencimento.lote')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
