# Generated by Django 5.0 on 2024-05-17 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
        ('vencimento', '0009_alter_lote_casa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='casa_atual',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='casa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vencimento.casa'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
