# Generated by Django 5.0 on 2024-06-01 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_remove_userprofile_casa_atual_userprofile_casa_and_more'),
        ('vencimento', '0012_lote_casa_destinada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_acessar', models.BooleanField(default=False)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_acesso', to='vencimento.casa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_casa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'casa')},
            },
        ),
    ]
