# Generated by Django 5.0 on 2024-06-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_acessocasa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acessocasa',
            options={'verbose_name': 'Acesso à Casa', 'verbose_name_plural': 'Acessos às Casas'},
        ),
        migrations.AlterField(
            model_name='acessocasa',
            name='pode_acessar',
            field=models.BooleanField(default=True),
        ),
    ]
